### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by ghfyyds** [RickyL-2000/ROSVOT#5]
运行最后的训练命令：CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python tasks/run.py --config configs/rosvot.yaml --exp_name test --reset 
时提示：
-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/suyuhang/anaconda3/envs/ROSVOT/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 90, in _wrap
    fn(i, *args)
  File "/data/samsungSSD/ghf/AST/ROSVOT/ROSVOT-main/utils/commons/trainer.py", line 137, in ddp_run
    self.run_single_process(task)
  File "/data/samsungSSD/ghf/AST/ROSVOT/ROSVOT-main/utils/commons/trainer.py", line 186, in run_single_process
    self.train()
  File "/data/samsungSSD/ghf/AST/ROSVOT/ROSVOT-main/utils/commons/trainer.py", line 261, in train
    self.evaluate(self.task, False, 'Sanity Val', max_batches=self.num_sanity_val_steps)
  File "/data/samsungSSD/ghf/AST/ROSVOT/ROSVOT-main/utils/commons/trainer.py", line 235, in evaluate
    output = task(*args)
  File "/home/suyuhang/anaconda3/envs/ROSVOT/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/suyuhang/anaconda3/envs/ROSVOT/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/samsungSSD/ghf/AST/ROSVOT/ROSVOT-main/utils/commons/ddp_utils.py", line 148, in forward
    self._run_ddp_forward(*inputs, **kwargs)
  File "/data/samsungSSD/ghf/AST/ROSVOT/ROSVOT-main/utils/commons/ddp_utils.py", line 161, in _run_ddp_forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/data/samsungSSD/ghf/AST/ROSVOT/ROSVOT-main/tasks/rosvot/task.py", line 235, in validation_step
    output_3 = self.model(mel=mel, word_bd=word_bd, note_bd=None, pitch=pitch_coarse, uv=uv,
  File "/home/suyuhang/anaconda3/envs/ROSVOT/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/suyuhang/anaconda3/envs/ROSVOT/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/samsungSSD/ghf/AST/ROSVOT/ROSVOT-main/modules/rosvot/rosvot.py", line 239, in forward
    note_bd = regulate_boundary(note_bd_logits, self.note_bd_threshold, self.note_bd_min_gap,
  File "/data/samsungSSD/ghf/AST/ROSVOT/ROSVOT-main/modules/rosvot/rosvot.py", line 88, in regulate_boundary
    bd_res[i, sum(non_padding[i]) - 1:] = 0
TypeError: only integer tensors of a single element can be converted to an index

**Comment by RickyL-2000** [comment]
我需要知道更多信息。

BTW，我猜 non_padding 的数据类型是 float，导致 sum() 了之后的 float 不能作为 index。试试把 sum() 之后的结果转化为 int，是否还会有这个问题。

**Comment by ghfyyds** [comment]
非常感谢昨天转换成int之后成功运行了
